[
    JKInner = JoinKind.Inner, JKLeft = JoinKind.LeftOuter, JKRight = JoinKind.RightOuter,
    JKFull = JoinKind.FullOuter, JKLAnti = JoinKind.LeftAnti, JKRAnti = JoinKind.RightAnti,
    GKLocal = GroupKind.Local, GKGlobal = GroupKind.Global,
    OccF = Occurrence.First, OccL = Occurrence.Last, OccA = Occurrence.All,
    QSNone = QuoteStyle.None, QSCsv = QuoteStyle.Csv,
    RMUp = RoundingMode.Up, RMDown = RoundingMode.Down, RMAway = RoundingMode.AwayFromZero,
    RMToward = RoundingMode.TowardZero, RMEven = RoundingMode.ToEven,
    MFError = MissingField.Error, MFIgnore = MissingField.Ignore, MFNull = MissingField.UseNull
]
