[
    A = #date(2021, 1, 31) - #date(2021, 1, 1),
    B = #date(2021, 1, 1) + #duration(1, 12, 0, 0),
    C = #datetime(2021, 1, 1, 10, 0, 0) - #datetime(2021, 1, 1, 8, 30, 0),
    D = #date(2021, 3, 1) & #time(6, 30, 0),
    E = #time(23, 0, 0) + #duration(0, 2, 0, 0),
    F = #date(2021, 1, 2) > #date(2021, 1, 1),
    G = #duration(0, 1, 0, 0) * 2.5,
    H = #duration(1, 0, 0, 0) / #duration(0, 12, 0, 0)
]
